<script src="{{ asset('vendor/gentelella-rtl/vendors/jquery/dist/jquery.min.js') }}"></script>
<script src="{{ asset('vendor/gentelella-rtl/vendors/bootstrap/dist/js/bootstrap.min.js') }}"></script>
<script src="{{ asset('vendor/gentelella-rtl/vendors/fastclick/lib/fastclick.js') }}"></script>
<script src="{{ asset('vendor/gentelella-rtl/vendors/nprogress/nprogress.js') }}"></script>
<script src="{{ asset('vendor/gentelella-rtl/vendors/bootstrap-progressbar/bootstrap-progressbar.min.js') }}"></script>
<script src="{{ asset('vendor/gentelella-rtl/vendors/iCheck/icheck.min.js') }}"></script>
<script src="{{ asset('vendor/gentelella-rtl/vendors/moment/min/moment.min.js') }}"></script>
<script src="{{ asset('vendor/izitoast/dist/js/iziToast.min.js') }}"></script>
<script src="{{ asset('vendor/gentelella-rtl/build/js/custom.min.js') }}"></script>
<script src="{{ asset('js/custom.js?v=1.0.5') }}"></script>